import random

number = random.randint(1,10)
tries=1


uname=input("hello What is your username: ")

print("hello" , uname + ".", )

question =input("Would you like to play a game? [Y/N]")
if question == "Y" or question == "y":
    print("i'm thinking of a number between 1 & 10")
    guess = int(input("Have a guess:"))
    print("Guess lower...")
    if guess < number:
        print("Guess higher...")
    while guess != number:
        tries += 1
        guess = int(input("Try again: "))
        if guess < number:
            print("Your're right! you win! The number was", number, "and it only", tries, "tries")

            if question == "n":
                print("oh okay ....")